plugin_prefix: "&b&lFactionsArcade &7>"
yeet2: 1

messages:
  testing: "Honestly idek bro wtf NO.1 #test#"
  no_permission: "#prefix# You do not have permission to use that command!"
  attention: "&b&m------------------------"
  name_faction: "#prefix# You have &b30 &7seconds to type your faction name in the &bchat&7!"
  name_faction_timeout: "#prefix# You didn't input your faction name in time!"
  faction_already_exists: "#prefix# That faction name is already in use! Please try again."
  generating_faction_island: "#prefix# Please wait while we &bgenerate &7your faction world!"
  teleporting_to_world: "#prefix# You have been teleported to your faction world!"
  given_schem_item: "#prefix# You now have a schematic wand! Left Click = POS1 | Right Click = POS2"
  pos1_selected: "#prefix# Position 1 set - #posLoc#"
  pos2_selected: "#prefix# Position 2 set - #posLoc#"
  not_in_fac: "#prefix# You're not in a faction"
  player_not_available: "#prefix# That player is not available!"
  target_already_in_faction: "#prefix# That player is already in a faction!"
  player_already_in_faction: "#prefix# You cannot join! You are already in a faction."
  faction_invite: "#prefix# You have been invited to join &b#senderFaction#&7! Please type &b/f join #senderFaction# &7if you wish to join!"
  faction_invite_help: "#prefix# &bNote&7: Factions are (cAsE sEnSiTiVe)"
  player_invited: "#prefix# You have successfully invited #playerInvited# to your faction!"
  not_invited_to_faction: "#prefix# You haven't been invited to that faction!"
  faction_joined: "#prefix# You successfully joined &b#joinedFaction#&7!"
  faction_name_not_alphanumeric: "#prefix# Your faction name can only include &bnumbers &7and &bletters&7!"
  player_not_in_own_fac: "#prefix# That player is not in your faction!"
  no_permission_promote: "#prefix# You cannot promote that player!"
  player_promoted: "#prefix# You have successfully promoted &b#targetPlayer#&7!"
  target_promoted: "#prefix# You have been promoted!"
  no_permission_kick: "#prefix# You cannot kick that player!"
  faction_leave: "#prefix# You have left your faction!"
  faction_kick: "#prefix# Successfully kicked #kickedPlayer# from your faction!"
  faction_kicked: "#prefix# You were kicked from your faction!"
  player_left_faction: "#prefix# &b#playerLeaving# &7Has left your faction island!"
  cannot_disband: "#prefix# You cannot disband your faction!"
  disband_broadcast: "&b&l#disbandedFaction# &7has been disbanded!"
  schem_saved: "#prefix# You successfully saved a schematic!"
  leader_cannot_leave: "#prefix# Leaders cannot leave their faction!"
  faction_home: "#prefix# Teleported to faction home."
  cannot_sethome: "#prefix# You cannot set faction home!"
  sethome_success: "#prefix# You set your faction home!"
  invalid_sethome: "#prefix# You cannot set your faction home here!"
  payout_message: "#prefix# You made &b$#amount# &7from the last 30 seconds of mining!"
  balance_message: "#prefix# Your current balance is &b$#amount#"
  balance_too_low: "#prefix# You don't have enough money for that upgrade!"
  upgrade_success: "#prefix# You successfully purchased an upgrade!"
  upgrade_already_purchased: "#prefix# You already have this upgrade!"
  
items:
  create_faction_item:
    item_name: "&7Create &b&lFaction Island&7!"
    material: "COAL_ORE"
  ftop_item:
    item_name: "&7Check out the &bTop &7Factions!"
    material: "GOLD_BLOCK"
  warps_item:
    item_name: "&7Open a list of &bWarps&7!"
    material: "STICK"
  schem_item:
    item_name: "&7Select a &bCuboid &7area!"
    material: "BLAZE_ROD"
    
#-------------
#Menus
#-------------

factionmenu:
  menusize: 54
  menun: "&7-==&bFaction Menu&7==-"
  items:
    warps_marker:
      name: "&b&lWarps"
      slot: 4
      material: "REDSTONE_TORCH_ON"
      lore:
      - "&7A list of all faction warps!"
    spawn_warp:
      name: "&b&lSpawn"
      slot: 10
      material: "GOLD_ORE"
      lore:
      - "&7Click to teleport!"
    mine_warp:
      name: "&b&lMine"
      slot: 11
      material: "DIAMOND_PICKAXE"
      lore:
      - "&7Click to teleport!"
    enchanter_warp:
      name: "&b&lEnchanter"
      slot: 12
      material: "BOOKSHELF"
      lore:
      - "&7Click to teleport!"
    blacksmith_warp:
      name: "&b&lBlacksmith"
      slot: 13
      material: "ANVIL"
      lore:
      - "&7Click to teleport!"
      
      
    upgrades_marker:
      name: "&b&lUpgrades"
      slot: 22
      material: "TORCH"
      lore:
      - "&7A list of all faction upgrades!"
    purchase_mine:
      name: "&b&lMine Tier 1 - $1,000"
      slot: 29
      material: "LOG"
      lore:
      - "&7Click to purchase Mine Tier 1"
    purchase_blacksmith:
      name: "&b&lBlacksmith Tier 1 - $3,000"
      slot: 30
      material: "LOG"
      lore:
      - "&7Click to purchase Blacksmith Tier 1"
    purchase_enchanter:
      name: "&b&lEnchanter Tier 1 - $5,000"
      slot: 31
      material: "LOG"
      lore:
      - "&7Click to purchase Enchanter Tier 1"
    purchase_commandcenter:
      name: "&b&lCommand Center Tier 1 - $10,000"
      slot: 32
      material: "LOG"
      lore:
      - "&7Click to purchase Command Center Tier 1"
      - "&4WARNING - &7Upon purchasing this upgrade, you will be susceptible to enemy attacks!"
    tier2_mine:
      name: "&b&lMine Tier 2 - $7,000"
      slot: 38
      material: "IRON_BLOCK"
      lore:
      - "&7Click to purchase Mine Tier 2"
    tier2_blacksmith:
      name: "&b&lBlacksmith Tier 2 - $10,000"
      slot: 39
      material: "IRON_BLOCK"
      lore:
      - "&7Click to purchase Blacksmith Tier 2"
    tier2_enchanter:
      name: "&b&lEnchanter Tier 2 - $12,000"
      slot: 40
      material: "IRON_BLOCK"
      lore:
      - "&7Click to purchase Enchanter Tier 2"
    tier2_commandcenter:
      name: "&b&lCommand Center Tier 2 - $20,000"
      slot: 41
      material: "IRON_BLOCK"
      lore:
      - "&7Click to purchase Command Center Tier 2"

#-------------
#Permissions
#-------------
#fa.schem.item